services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: api
    image: ghcr.io/spyrosmoux/api
    build:
      context: .
    environment:
      API_PORT: ${API_PORT}
      GH_WEBHOOK_SECRET: ${GH_WEBHOOK_SECRET}
      GH_TOKEN: ${GH_TOKEN}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "8080:8080"
