variables:
  REGISTRY: ghcr.io
  IMAGE_NAME: jacksndecks-api

jobs:
  - name: Checkout Repository
    steps:
      - name: Checkout Repository
        run: |
          git clone https://github.com/Jacks-Decks/jacks-n-decks-api.git
          cd jacks-n-decks-api/
          git checkout origin/develop
          sleep 30

  - name: Build Docker image
    steps:
      - name: build docker image
        run: |
          cd jacks-n-decks-api/
          docker build -t ${REGISTRY}/${IMAGE_NAME} .

